#!/usr/bin/env python3
"""
Edge calibration: what has a promised edge actually paid?  Reads data/consensus_bets.json (every second-half bet at 3%+ edge after
fees from build_consensus.py: books -> Kalshi, Kalshi -> books, Kalshi ladder) and compares, per promised-edge bucket, the edge the
engine promised with the edge the bets realized (realized edge = return per unit x cost, in probability points).

Result in docs/edge-calibration.md. The Edges page sizes stakes on the realistic edge (REAL_EDGE in ui/projections.template.html is
the 'consensus + model' table printed here). Re-run after build_consensus.py.

  python3 nba/scripts/calibrate_edge.py
"""
import collections, json, math, os, statistics
HERE = os.path.dirname(os.path.abspath(__file__)); DATA = os.path.join(HERE, '..', 'data'); DOCS = os.path.join(HERE, '..', 'docs')
j = json.load(open(os.path.join(DATA, 'consensus_bets.json')))
rows = [dict(zip(j['cols'], r)) for r in j['rows']]
BUCKETS = [(0.03, 0.04), (0.04, 0.05), (0.05, 0.07), (0.07, 0.10), (0.10, 0.15), (0.15, 9)]


def bucket(xs):
    n = len(xs)
    if not n:
        return None
    pe = sum(x['edge'] for x in xs) / n
    re_ = sum(x['ret'] * x['cost'] for x in xs) / n
    g = collections.defaultdict(list)
    for x in xs:
        g[x['gid']].append(x['ret'] * x['cost'] - x['edge'])
    gm = [statistics.mean(v) for v in g.values()]
    se = statistics.stdev(gm) / math.sqrt(len(gm)) if len(gm) > 1 else float('nan')
    return {'n': n, 'games': len(g), 'promised': pe, 'realized': re_, 'ci': 1.96 * se, 'keep': re_ / pe}


def table(xs):
    out = ['| Promised edge | Bets | Games | Promised (pts) | Realized (pts) | 95% range | Kept |', '|---|---|---|---|---|---|---|']
    pts = []
    for lo, hi in BUCKETS:
        b = bucket([r for r in xs if lo <= r['edge'] < hi])
        if b:
            out.append(f"| {lo*100:.0f}{'-' + format(hi*100, '.0f') if hi < 9 else '+'} pts | {b['n']:,} | {b['games']} | {b['promised']*100:.1f} | {b['realized']*100:.1f} | ±{b['ci']*100:.1f} | {b['keep']:.0%} |")
            pts.append([round(b['promised'], 3), round(b['realized'], 3)])
    return out, pts


md = ['# Edge calibration', '', 'Generated by `nba/scripts/calibrate_edge.py` from `data/consensus_bets.json` (second-half bets by tip time, 2025-26, 3%+ edge after fees).',
      'Realized edge = return per unit x cost, in probability points, so it is directly comparable with the promised edge. The 95% range is clustered by game.', '']
for fair in ('consensus + model', 'consensus'):
    xs = [r for r in rows if r['fair'] == fair]
    t, pts = table(xs)
    md += [f'## Fair = {fair}', f'{len(xs):,} bets.', ''] + t + ['', f'`REAL_EDGE = {pts}`' if fair == 'consensus + model' else '', '']
    for test in ('books_to_kalshi', 'kalshi_to_books', 'kalshi_ladder'):
        s = [r for r in xs if r['test'] == test]
        b = bucket(s)
        if b:
            md.append(f"- {test}: {b['n']:,} bets, promised {b['promised']*100:.1f} pts, realized {b['realized']*100:.1f} pts (±{b['ci']*100:.1f}), kept {b['keep']:.0%}")
    md.append('')
md += ['## Reading it', '',
       'A promised edge does not keep paying more as it grows: past about 4 points, realized edge climbs slowly (a promised 8 pts realized about 4; a promised 12 about 5).',
       'The range around each bucket is wide (a few points), so the table is a haircut, not a forecast. The page sizes stakes on it and shows it beside the promised edge.',
       'Kalshi -> books is where promises fail hardest (promised 20 pts, realized about 0), in line with its NO-GO verdict.', '']
open(os.path.join(DOCS, 'edge-calibration.md'), 'w').write('\n'.join(md))
print('\n'.join(md))
